// AUTO-GENERATED by scripts/import-product-images.ts — product images in productNames order.
export const productImages: Record<string, string[]> = {
  "primary-tillage": [
    "/products/primary-tillage/1-super-seeder-coulter-disc-type.webp",
    "/products/primary-tillage/2-rotavator-machine-export-model.webp",
    "/products/primary-tillage/3-gobal-disc-harrow.webp",
    "/products/primary-tillage/4-tandem-disc-harrow.webp",
    "/products/primary-tillage/5-disc-plough-pipe-frame.webp",
    "/products/primary-tillage/6-post-hole-digger-machine.webp",
    "/products/primary-tillage/7-mould-board-plough-chisel-model.webp",
    "/products/primary-tillage/8-mould-board-plough-regular-model.webp",
    "/products/primary-tillage/9-chisel-plough-3-tines.webp",
    "/products/primary-tillage/10-chisel-plough-5-tines.webp",
    "/products/primary-tillage/11-mini-power-tiller.webp",
    "/products/primary-tillage/12-cultivator-machine.webp",
    "/products/primary-tillage/13-cultivator-spring-pipe-cover-type.webp",
    "/products/primary-tillage/14-cultivator-z-frame-machine.webp"
  ],
  "secondary-tillage": [
    "/products/secondary-tillage/1-laser-land-leveller-machine.webp",
    "/products/secondary-tillage/2-garlic-bed-shaper-with-seed-placement-pointer.webp",
    "/products/secondary-tillage/3-bed-shaper-planter-with-fertilizer-system-dibbler-type-maize-cotton.webp",
    "/products/secondary-tillage/4-multi-crop-bed-shaper-cum-planter.webp",
    "/products/secondary-tillage/5-automatic-potato-planter-machine.webp",
    "/products/secondary-tillage/6-vegetable-ridger-with-row-markers.webp",
    "/products/secondary-tillage/7-border-disc.webp",
    "/products/secondary-tillage/8-single-bed-shaper.webp",
    "/products/secondary-tillage/9-border-ditcher-blade.webp",
    "/products/secondary-tillage/10-bed-shaper.webp",
    "/products/secondary-tillage/11-ditcher-with-press-system.webp",
    "/products/secondary-tillage/12-ditcher-with-side-disc.webp"
  ],
  "seeding-planting": [
    "/products/seeding-planting/1-super-seeder-coulter-disc-type.webp",
    "/products/seeding-planting/2-zero-tillage-seed-drill.webp",
    "/products/seeding-planting/3-multi-crop-no-till-planter.webp",
    "/products/seeding-planting/4-bed-shaper-planter-with-fertilizer-system-dibbler-type-maize-cotton.webp",
    "/products/seeding-planting/5-direct-seeding-rice-drill-dsr.webp",
    "/products/seeding-planting/6-multi-crop-bed-shaper-cum-planter.webp",
    "/products/seeding-planting/7-seed-drill-rabi-model.webp",
    "/products/seeding-planting/8-automatic-potato-planter-machine.webp",
    "/products/seeding-planting/9-rice-drum-seeder.webp",
    "/products/seeding-planting/10-vegetable-seedling-transplanter.webp",
    "/products/seeding-planting/11-hand-push-seeder.webp",
    "/products/seeding-planting/12-portable-seeder.webp",
    "/products/seeding-planting/13-vegetable-seeder-rollers-type.webp",
    "/products/seeding-planting/14-vegetable-seeder-spoon-type.webp",
    "/products/seeding-planting/15-fertilizer-spreader.webp"
  ],
  "harvesting-cutting": [
    "/products/harvesting-cutting/1-wheat-straw-chopper-machine.webp",
    "/products/harvesting-cutting/2-mini-tractor-with-2-type-reaper.webp",
    "/products/harvesting-cutting/3-multi-purpose-reaper-machine.webp",
    "/products/harvesting-cutting/4-reaper-machine-export-model.webp",
    "/products/harvesting-cutting/5-barseem-harvester-machine.webp",
    "/products/harvesting-cutting/6-lawn-grass-mower-machine.webp",
    "/products/harvesting-cutting/7-multi-purpose-walking-type-reaper.webp",
    "/products/harvesting-cutting/8-back-pack-weeder-brush-cutter.webp",
    "/products/harvesting-cutting/9-brush-cutter-shoulder-type.webp",
    "/products/harvesting-cutting/10-olive-fruit-harvester.webp",
    "/products/harvesting-cutting/11-automatic-potato-digger.webp"
  ],
  "post-harvest-processing": [
    "/products/post-harvest-processing/1-wheat-straw-chopper-machine.webp",
    "/products/post-harvest-processing/2-silage-machine-conveyor-type.webp",
    "/products/post-harvest-processing/3-banana-shredder-machine.webp",
    "/products/post-harvest-processing/4-maize-sheller.webp",
    "/products/post-harvest-processing/5-seed-grader-cleaner-machine.webp",
    "/products/post-harvest-processing/6-wheat-thresher-machine.webp"
  ],
  "manual-walk-behind": [
    "/products/manual-walk-behind/1-rice-drum-seeder.webp",
    "/products/manual-walk-behind/2-vegetable-seedling-transplanter.webp",
    "/products/manual-walk-behind/3-hand-push-seeder.webp",
    "/products/manual-walk-behind/4-portable-seeder.webp",
    "/products/manual-walk-behind/5-vegetable-seeder-rollers-type.webp",
    "/products/manual-walk-behind/6-vegetable-seeder-spoon-type.webp",
    "/products/manual-walk-behind/7-mechanical-rice-weeder.webp",
    "/products/manual-walk-behind/8-mini-power-tiller.webp",
    "/products/manual-walk-behind/9-multi-purpose-walking-type-reaper.webp",
    "/products/manual-walk-behind/10-back-pack-weeder-brush-cutter.webp",
    "/products/manual-walk-behind/11-brush-cutter-shoulder-type.webp",
    "/products/manual-walk-behind/12-olive-fruit-harvester.webp"
  ],
  "others": [
    "/products/others/1-mini-tractor-with-2-type-reaper.webp",
    "/products/others/2-manual-cono-weeder.webp",
    "/products/others/3-mechanical-rice-weeder.webp",
    "/products/others/4-fertilizer-spreader.webp"
  ]
}
