/**
 * One-time importer: maps the "Category & Machines WEBP" source folders to clean,
 * URL-safe product image paths, copies them into public/products/<slug>/, updates
 * every product's image in the DB, refreshes each category's image+gallery, and
 * writes lib/product-images.ts so the seed stays reproducible.
 *
 * Run: npx tsx scripts/import-product-images.ts
 */
import { PrismaClient } from '@prisma/client'
import { existsSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from 'fs'
import path from 'path'
import { categories, getCategoryProducts } from '../lib/site-data'

const prisma = new PrismaClient()

const PUBLIC = path.join(process.cwd(), 'public')
const SRC_ROOT = path.join(PUBLIC, 'Category & Machines WEBP')

// Source folders are prefixed A.–G.; map that letter to our category slug.
const LETTER_TO_SLUG: Record<string, string> = {
  A: 'primary-tillage',
  B: 'secondary-tillage',
  C: 'seeding-planting',
  D: 'harvesting-cutting',
  E: 'post-harvest-processing',
  F: 'manual-walk-behind',
  G: 'others',
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function leadingNumber(name: string): number {
  const m = name.match(/^\s*(\d+)/)
  return m ? parseInt(m[1], 10) : 9999
}

async function main() {
  if (!existsSync(SRC_ROOT)) throw new Error(`Source folder not found: ${SRC_ROOT}`)

  // slug -> source folder absolute path
  const folderBySlug = new Map<string, string>()
  for (const dir of readdirSync(SRC_ROOT, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue
    const letter = dir.name.trim().charAt(0).toUpperCase()
    const slug = LETTER_TO_SLUG[letter]
    if (slug) folderBySlug.set(slug, path.join(SRC_ROOT, dir.name))
  }

  const imageMap: Record<string, string[]> = {}

  for (const cat of categories) {
    const folder = folderBySlug.get(cat.slug)
    if (!folder) {
      console.warn(`⚠ no source folder for ${cat.slug}`)
      continue
    }

    // ordered source files (by leading number) + ordered product names
    const files = readdirSync(folder)
      .filter((f) => f.toLowerCase().endsWith('.webp'))
      .sort((a, b) => leadingNumber(a) - leadingNumber(b))
    const names = getCategoryProducts(cat.slug).map((p) => p.name)

    if (files.length !== names.length) {
      console.warn(`⚠ ${cat.slug}: ${files.length} images vs ${names.length} products — mapping by index up to the shorter list`)
    }

    const destDir = path.join(PUBLIC, 'products', cat.slug)
    mkdirSync(destDir, { recursive: true })

    const webPaths: string[] = []
    const count = Math.min(files.length, names.length)
    for (let i = 0; i < count; i++) {
      const name = names[i]
      const destName = `${i + 1}-${slugify(name)}.webp`
      copyFileSync(path.join(folder, files[i]), path.join(destDir, destName))
      const webPath = `/products/${cat.slug}/${destName}`
      webPaths.push(webPath)

      // Update the matching DB product (by category + exact name).
      const product = await prisma.product.findFirst({
        where: { name, category: { slug: cat.slug }, deletedAt: null },
      })
      if (product) {
        await prisma.productImage.deleteMany({ where: { productId: product.id } })
        await prisma.productImage.create({ data: { productId: product.id, path: webPath, position: 0 } })
      }
    }

    imageMap[cat.slug] = webPaths

    // Refresh category primary image + gallery from its products.
    await prisma.category.updateMany({
      where: { slug: cat.slug },
      data: { image: webPaths[0] ?? null, gallery: webPaths.slice(0, 3) },
    })

    console.log(`✓ ${cat.slug}: ${count} images imported`)
  }

  // Emit a reproducible map for the seed.
  const fileBody =
    `// AUTO-GENERATED by scripts/import-product-images.ts — product images in productNames order.\n` +
    `export const productImages: Record<string, string[]> = ${JSON.stringify(imageMap, null, 2)}\n`
  writeFileSync(path.join(process.cwd(), 'lib', 'product-images.ts'), fileBody)
  console.log('✓ wrote lib/product-images.ts')
}

main()
  .catch((e) => {
    console.error('❌ import failed:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
